---
- name: Install Docker packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker.io
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is enabled
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
